### ISSUE TITLE
Use Skip instead of Pass

### ISSUE THREAD

**Issue by techspaniard** [tenable/audit_scripts#5]
Would it be possible to give users the ability to call out how audit exceptions are marked? For example, instead of always marking prior Failed items as Passed allow the use the Skipped option? Based off the HTML reports from Tenable IO, I am assuming Skipped it an potential option outside of the normal Passed or Failed.

**Comment by streckc** [comment]
I'm assuming this is a question on the baseline script, and that is the feature this comment is responding to.

In the compliance plugins that do the processing, all plugins support PASSED, FAILED, and WARNING.  A couple of the plugins have some additional results such as ERROR and INFO, and only the Unix plugin has a result of SKIPPED.  To enable the SKIPPED result in all plugins and have that flow to Tenable.IO and SC properly would be a fairly large Feature Request.

In addition to that, being able to change how the known_good feature does its evaluation, defining how to determine if a result should be PASSED or SKIPPED, or change the way the evaluation is done by audit file or check item, may offer challenges.

Since these are in how the Tenable plugins evaluate the audit file, and this site is for updating the audit files, you will have to open a feature request with Tenable Tech Support in order to try an pursue these suggestions.

Does this give you guidance on what needs to be done, or did I miss the target of the question?

**Comment by techspaniard** [comment]
Correct this was intended for the baseline script. Your response did give me some guidance. All in all, sounds like I need to open a feature request. The core goal I am trying to accomplish is to easily identify which CIS controls we have been accepted by our organization from risk a perspective within an output report, so SKIPPED seemed like a natural choice. Thanks for your fast response!

**Comment by streckc** [comment]
I'm thinking that Tenable.IO or SC may have recast rules that can state you 'accept the risk', but the recast may be to just passing.

I'm closing this issue as it will have to be a Tenable FR through support to get progress on it.
